# Helix config for LDIF files
# Uses the tree-sitter-ldif grammar from GitHub

[[language]]
name          = "ldif"
scope         = "source.ldif"
file-types    = ["ldif"]
roots         = []
comment-token = "#"
grammar       = "ldif"

[[grammar]]
name       = "ldif"
source.git = "https://github.com/kjanat/tree-sitter-ldif.git"
source.rev = "f6d1c3a755a89251f5b5f8abdcae3f3093243cfb"
